ARG BUILD_ENV

FROM nginx:1.19-alpine as build_prod

ONBUILD COPY ./services/proxy/conf/prod.nginx.conf /etc/nginx/conf.d/default.conf

FROM nginx:1.19-alpine as build_dev

ONBUILD COPY ./services/proxy/conf/dev.nginx.conf /etc/nginx/conf.d/default.conf

FROM nginx:1.19-alpine as build_mini

ONBUILD COPY ./services/proxy/conf/mini.nginx.conf /etc/nginx/conf.d/default.conf

FROM build_${BUILD_ENV}

COPY ./services/proxy/index.html /usr/share/nginx/html

EXPOSE 8080
