apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  SERVER_NAME: "ioManager"
  SERVER_PORT: "4356"
  SERVER_TOKEN_SECRET: "mV|GuHok*+6N<C5~S|I0Wy^"
  SERVER_DB_CONNECTION_STRING: mongodb://flashio:totallysecret@server-db-svc.default:27017/g42-home?authSource=admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MONGO_INITDB_ROOT_USERNAME: "flashio"
  MONGO_INITDB_ROOT_PASSWORD: "totallysecret"